/**
 * Contenido del VI Congreso Internacional Intracom (Tenerife, diciembre de 2026),
 * en español, inglés y portugués. Aquí se edita todo el texto de la web: el diseño
 * no lleva frases escritas dentro.
 */
window.INTRACOM_CONTENT = {
  es: {
    lang: "es",
    meta: {
      title: "VI Congreso Internacional Intracom · Tenerife 2026",
      description:
        "VI Congreso Internacional de Investigación y Transferencia en Comunicación y Divulgación de las Ciencias. Universidad de La Laguna, 2 a 4 de diciembre de 2026. Propuestas hasta el 25 de octubre.",
    },
    nav: {
      congreso: "El congreso",
      mesas: "Mesas temáticas",
      participacion: "Participación",
      tarifas: "Tarifas",
      publicaciones: "Publicaciones",
      organizacion: "Organización",
      sede: "Sede",
      cta: "Inscríbete",
    },
    hero: {
      eyebrow: "VI Congreso Internacional · Tenerife 2026",
      title: "Derecho y comunicación crítica",
      titleAccent: "frente al algoritmo",
      lead: "Congreso Internacional de Investigación y Transferencia en Comunicación y Divulgación de las Ciencias.",
      chips: [
        { label: "Presencial", value: "3 y 4 de diciembre de 2026" },
        { label: "Online", value: "2 de diciembre de 2026" },
        { label: "Sede", value: "Universidad de La Laguna · Tenerife" },
      ],
      cta1: "Presenta tu propuesta",
      cta2: "Ver las mesas temáticas",
      bar: "Envío de comunicaciones abierto hasta el 25 de octubre de 2026",
      barCta: "Cómo participar →",
    },
    stats: [
      { n: "VI", l: "edición del congreso" },
      { n: "6", l: "mesas temáticas" },
      { n: "2", l: "talleres ANECA incluidos" },
      { n: "3", l: "idiomas de participación" },
    ],
    about: {
      label: "01 · Presentación",
      title: "Repensar la comunicación cuando el algoritmo decide",
      paragraphs: [
        "Vivimos un momento marcado por transformaciones tecnológicas, culturales y políticas que están alterando las formas de producir, distribuir y legitimar la información. La inteligencia artificial generativa, el poder de las plataformas y la automatización algorítmica han configurado un ecosistema mediático de hiperconectividad, sobreabundancia informativa y aceleración de la opinión pública.",
        "En ese contexto, la desinformación, los discursos de odio, la polarización y la manipulación emocional de las audiencias son algunos de los principales desafíos para las democracias. La crisis de confianza en las instituciones y la expansión de narrativas extremistas obligan a repensar las relaciones entre comunicación, derechos fundamentales y ciudadanía digital.",
        "La inteligencia artificial intensifica esas tensiones: herramientas capaces de generar textos, imágenes, vídeos o voces sintéticas plantean interrogantes sobre la veracidad de los contenidos, la autoría, la responsabilidad jurídica y los límites éticos de la automatización comunicativa.",
        "Por eso proponemos un espacio de reflexión interdisciplinar que analice críticamente estas transformaciones desde perspectivas jurídicas, educativas, éticas y sociales, con la defensa de los derechos humanos y de una comunicación democrática como eje.",
      ],
    },
    mesas: {
      label: "02 · Mesas temáticas",
      title: "Seis líneas para repensar la comunicación digital",
      lead: "Las mesas son permeables: una propuesta puede cruzar dos o más ejes. Indícalo al enviarla.",
      items: [
        {
          eje: "Inteligencia artificial",
          title: "Inteligencia artificial, ecosistemas mediáticos y gobernanza digital",
          desc: "El impacto de la inteligencia artificial en los procesos de comunicación, información y producción cultural, y las transformaciones que introduce en los ecosistemas mediáticos.",
          tags: ["Ética algorítmica", "Deepfakes", "Gobernanza digital", "Automatización", "Creación cultural"],
        },
        {
          eje: "Democracia",
          title: "Desinformación, democracia y calidad del debate público",
          desc: "Dinámicas de la desinformación, la posverdad y la polarización política: estrategias de manipulación narrativa y emocional, el papel de las plataformas y las herramientas de verificación.",
          tags: ["Posverdad", "Fact-checking", "Polarización", "Plataformas"],
        },
        {
          eje: "Derechos",
          title: "Derechos digitales, regulación y ciudadanía en red",
          desc: "Retos jurídicos, políticos y sociales de la transformación digital: regulación de plataformas e inteligencia artificial, privacidad, propiedad intelectual y responsabilidad de los actores digitales.",
          tags: ["Privacidad", "Protección de datos", "Propiedad intelectual", "Regulación"],
        },
        {
          eje: "Diversidad",
          title: "Diversidad, comunicación inclusiva y culturas digitales",
          desc: "Relaciones entre comunicación, identidades culturales y transformación social en redes y plataformas: discursos de odio, discriminación y violencia simbólica, junto a estrategias de comunicación inclusiva.",
          tags: ["Discursos de odio", "Inclusión", "Representación", "Comunidades", "Culturas digitales"],
        },
        {
          eje: "Aprendizaje",
          title: "Educación mediática, alfabetización digital y transferencia del conocimiento",
          desc: "Formación crítica ante los desafíos tecnológicos: alfabetización mediática y algorítmica, innovación docente, ciudadanía digital y divulgación científica.",
          tags: ["Alfabetización mediática", "Innovación docente", "Divulgación científica", "Ciudadanía digital"],
        },
        {
          eje: "Futuro",
          title: "Ética, sostenibilidad y futuro de la comunicación",
          desc: "Desafíos éticos, democráticos y humanísticos de la hiperconectividad: sostenibilidad digital, responsabilidad social y derechos fundamentales en entornos automatizados.",
          tags: ["Sostenibilidad digital", "Responsabilidad social", "Prospectiva", "Derechos fundamentales"],
        },
      ],
    },
    aneca: {
      label: "Novedad · VI edición",
      title: "Seminario de preparación de acreditaciones ANECA",
      lead: "Este año, por el mismo coste de participación, puedes asistir a un taller práctico de dos horas orientado a preparar tu acreditación ante la Comisión de Ciencias Sociales II de ANECA.",
      talleres: [
        { dia: "3 de diciembre", title: "Profesor/a Titular de Universidad", desc: "Taller práctico de dos horas dirigido a la preparación de la acreditación a Profesor/a Titular." },
        { dia: "4 de diciembre", title: "Catedrático/a de Universidad", desc: "Taller práctico de dos horas dirigido a la preparación de la acreditación a Catedrático/a de Universidad." },
      ],
      puntos: [
        { n: "i", t: "Criterios de evaluación", d: "Atención especial a los criterios de la Comisión de Ciencias Sociales II." },
        { n: "ii", t: "Preparación de la solicitud", d: "Cómo abordar la preparación del expediente de acreditación." },
        { n: "iii", t: "Resolución de dudas", d: "Espacio abierto para las preguntas de quienes participan." },
      ],
      nota: "Incluido en el coste de participación en Intracom 2026.",
    },
    participacion: {
      label: "03 · Participación",
      title: "Tres formas de participar",
      lead: "Presenta tu propuesta en español, inglés o portugués.",
      items: [
        { tag: "Presencial", title: "Congresista presencial", desc: "Comparte tu investigación en la sede del congreso, con una comunicación científica o un póster, y participa en las sesiones." },
        { tag: "Online en directo", title: "Congresista online", desc: "Participa desde cualquier lugar del mundo en la jornada virtual del 2 de diciembre, sin desplazarte." },
        { tag: "Online en diferido", title: "Comunicación grabada", desc: "Envía el vídeo de tu comunicación: se presenta durante el congreso y recibes el material y los comentarios después." },
      ],
      requisitos: {
        title: "Qué debe incluir tu propuesta",
        items: [
          { t: "Título", d: "Claro y sin mayúsculas sostenidas." },
          { t: "Resumen en PDF", d: "Entre 300 y 500 palabras: objetivos, método, resultados y conclusiones." },
          { t: "Palabras clave", d: "De cuatro a seis términos." },
          { t: "Mesa temática", d: "La principal; si cruza varias, indícalo." },
          { t: "Autoría", d: "Nombre, filiación, país y correo de cada firmante." },
        ],
      },
    },
    tarifas: {
      label: "04 · Tarifas",
      title: "Elige tu inscripción",
      lead: "Cada persona firmante se inscribe con la tarifa que le corresponde. Precios con impuestos incluidos.",
      presencial: "Modalidad presencial",
      online: "Modalidad online",
      items: [
        { grupo: "presencial", precio: "160 €", title: "Congresista presencial", desc: "Primer firmante y firmantes adicionales que asisten. Incluye los talleres ANECA.", destacada: true },
        { grupo: "presencial", precio: "210 €", title: "Con actividad de networking", desc: "Todos los derechos de la inscripción básica más una cena de trabajo con otras personas participantes." },
        { grupo: "presencial", precio: "260 €", title: "Con publicación científica", desc: "Incluye el derecho a participar en la evaluación por pares ciegos. El pago no garantiza la publicación." },
        { grupo: "presencial", precio: "310 €", title: "Inscripción completa", desc: "Para primeros firmantes presenciales: networking y publicación en editorial del ranking SPI." },
        { grupo: "presencial", precio: "120 €", title: "Firmante adicional sin asistencia", desc: "Para firmantes de una comunicación presencial que no asisten al congreso." },
        { grupo: "online", precio: "100 €", title: "Inscripción básica online", desc: "Participación en la jornada online del 2 de diciembre, en directo o en diferido." },
        { grupo: "online", precio: "80 €", title: "Firmante adicional online", desc: "Para firmantes de una comunicación presentada en modalidad online." },
        { grupo: "online", precio: "200 €", title: "Online con publicación", desc: "Modalidad online con derecho a participar en la evaluación por pares para publicación." },
      ],
      cta: "Inscribirme",
      nota: "La inscripción se abre cuando el comité acepta tu propuesta. La factura se descarga desde tu área privada en cuanto se confirma el pago.",
    },
    fechas: {
      label: "05 · Calendario",
      title: "Fechas clave",
      items: [
        { fecha: "25 de octubre de 2026", t: "Cierre del envío de propuestas", d: "Comunicaciones, pósteres y presentaciones de libro." },
        { fecha: "28 de octubre de 2026", t: "Notificación del resultado", d: "El comité científico comunica su decisión." },
        { fecha: "31 de octubre de 2026", t: "Cierre de inscripción", d: "Último día para formalizar el pago." },
        { fecha: "10 de noviembre de 2026", t: "Programa definitivo", d: "Publicación del programa del congreso." },
        { fecha: "2 a 4 de diciembre de 2026", t: "Celebración del congreso", d: "Jornada online el 2; presencial el 3 y el 4." },
      ],
    },
    publicaciones: {
      label: "06 · Publicaciones",
      title: "De la comunicación a la publicación científica",
      paragraphs: [
        "Participar en el congreso y publicar son dos procesos independientes: presentar una comunicación no obliga a enviar después el texto completo.",
        "Quien quiera optar a publicación remite su texto completo en el plazo previsto, adaptado a las normas editoriales, y se somete a evaluación por pares ciegos. La gestión editorial tiene un coste adicional de 100 € por comunicación, no por firmante, que puede asumir cualquiera de las personas firmantes.",
        "Los trabajos que superan la evaluación se publican en editoriales académicas colaboradoras. Si una propuesta no es aceptada, puede incorporarse, previa valoración científica, a volúmenes colectivos de Intracom o a las revistas vinculadas al portal.",
      ],
      editoriales: { title: "Editoriales colaboradoras", items: ["Tirant lo Blanch", "Dykinson", "Fragua", "Tecnos"] },
      revistas: { title: "Revistas de esta edición", items: ["Dígitos", "Perspectivas de la Comunicación", "Intracom Journal"] },
    },
    organizacion: {
      label: "07 · Organización",
      title: "Quién hay detrás",
      grupos: [
        {
          title: "Equipo de dirección",
          personas: [
            ["José Antonio Batista", "Universidad de La Laguna"],
            ["Juan Carlos Suárez Villegas", "Universidad de Sevilla"],
            ["Ana Regina Rego", "Universidade Federal do Piauí"],
            ["Sergio Siverio Luis", "Universidad de La Laguna"],
          ],
        },
        {
          title: "Comité científico",
          personas: [
            ["Carmen Peñafiel", "Universidad del País Vasco"],
            ["Arantxa Capdevila", "Universitat Rovira i Virgili"],
            ["Anna Tous", "Universidad Autónoma de Barcelona"],
            ["Daniel Cabrera", "Universidad de Zaragoza"],
            ["Rogério Christofoletti", "Universidade Federal de Santa Catarina"],
            ["Daniel López Rubio", "Universidad de La Laguna"],
            ["Hugo Aznar", "Universidad CEU Cardenal Herrera"],
            ["Antón Castromil", "Universidad Complutense de Madrid"],
            ["Paola Panarese", "Sapienza Università di Roma"],
            ["Bella Palomo", "Universidad de Málaga"],
            ["Carolina Moreno", "Universidad de Valencia"],
            ["Laura Iannelli", "Università degli Studi di Sassari"],
            ["Lucas Sebastián De Érice Aranda", "Universidad de La Laguna"],
            ["Nora Rodríguez García", "Universidad de La Laguna"],
            ["Laura Casanova Martín", "Universidad de La Laguna"],
            ["Michele Goulart", "Universidade Federal do Paraná"],
            ["Gianpietro Mazzoleni", "Università degli Studi di Milano"],
            ["Marian Chaparro", "Universidad Complutense de Madrid"],
            ["Fernando Paulino Oliveira", "Universidad de Brasilia"],
            ["Caterina Foà", "Instituto Universitário de Lisboa"],
          ],
        },
        {
          title: "Secretaría y organización",
          personas: [
            ["Sergio Marín Conejo", "Secretaría técnica · Universidad de Sevilla"],
            ["Jesús Cruz Álvarez", "Organización · Portal Intracom"],
            ["Ignacio Caballero García", "Organización · Universidad de La Laguna"],
            ["Ana Ruiz Soto", "Web · Universidad de Málaga"],
          ],
        },
      ],
    },
    sede: {
      label: "08 · Sede",
      title: "Universidad de La Laguna, Tenerife",
      paragraphs: [
        "El congreso se celebra en la Facultad de Ciencias Sociales y de la Comunicación, en el Campus de Guajara, con la colaboración de la sede de IACTEC del Instituto de Astrofísica de Canarias.",
        "Tenerife se eligió por su posición entre tres continentes, un símil del carácter iberoamericano del congreso, y por su proximidad y sensibilidad hacia los problemas del sur global. La idiosincrasia canaria, multicultural y abierta, crea un ambiente propicio para el encuentro entre colegas.",
      ],
      direccion: "Campus de Guajara · Universidad de La Laguna · Santa Cruz de Tenerife, Islas Canarias",
      mapa: "Ver ubicación en el mapa →",
    },
    footer: {
      desc: "VI Congreso Internacional de Investigación y Transferencia en Comunicación y Divulgación de las Ciencias.",
      menu: "Secciones",
      contacto: "Contacto",
      red: "Congresos de la red",
      legal: "Aviso legal",
      privacidad: "Privacidad",
      cookies: "Cookies",
      condiciones: "Condiciones de inscripción",
      copy: "Congreso Intracom · Portal Iberoamericano de la Transferencia del Conocimiento",
      portal: "Portal Intracom ↗",
    },
  },

  en: {
    lang: "en",
    meta: {
      title: "6th Intracom International Conference · Tenerife 2026",
      description:
        "6th International Conference on Research and Knowledge Transfer in Communication and Science Communication. University of La Laguna, 2–4 December 2026. Proposals until 25 October.",
    },
    nav: {
      congreso: "The conference",
      mesas: "Thematic panels",
      participacion: "Participation",
      tarifas: "Fees",
      publicaciones: "Publications",
      organizacion: "Organisation",
      sede: "Venue",
      cta: "Register",
    },
    hero: {
      eyebrow: "6th International Conference · Tenerife 2026",
      title: "Law and critical communication",
      titleAccent: "in the face of the algorithm",
      lead: "International Conference on Research and Knowledge Transfer in Communication and Science Communication.",
      chips: [
        { label: "On site", value: "3 and 4 December 2026" },
        { label: "Online", value: "2 December 2026" },
        { label: "Venue", value: "University of La Laguna · Tenerife" },
      ],
      cta1: "Submit your proposal",
      cta2: "See the thematic panels",
      bar: "Call for papers open until 25 October 2026",
      barCta: "How to take part →",
    },
    stats: [
      { n: "6th", l: "edition of the conference" },
      { n: "6", l: "thematic panels" },
      { n: "2", l: "ANECA workshops included" },
      { n: "3", l: "languages of participation" },
    ],
    about: {
      label: "01 · About",
      title: "Rethinking communication when the algorithm decides",
      paragraphs: [
        "We live in a moment shaped by technological, cultural and political change that is altering how information is produced, distributed and legitimised. Generative artificial intelligence, the power of platforms and algorithmic automation have created a media ecosystem of hyperconnectivity, information overload and accelerated public opinion.",
        "In that context, disinformation, hate speech, polarisation and the emotional manipulation of audiences are among the main challenges facing democracies. The crisis of trust in institutions and the spread of extremist narratives call for a rethink of the relationship between communication, fundamental rights and digital citizenship.",
        "Artificial intelligence intensifies these tensions: tools that generate text, images, video or synthetic voices raise questions about the truthfulness of content, authorship, legal liability and the ethical limits of automated communication.",
        "We therefore propose a space for interdisciplinary reflection that examines these changes critically from legal, educational, ethical and social perspectives, with the defence of human rights and democratic communication at its centre.",
      ],
    },
    mesas: {
      label: "02 · Thematic panels",
      title: "Six lines for rethinking digital communication",
      lead: "The panels are permeable: a proposal may cross two or more. Say so when you submit it.",
      items: [
        {
          eje: "Artificial intelligence",
          title: "Artificial intelligence, media ecosystems and digital governance",
          desc: "The impact of artificial intelligence on communication, information and cultural production, and the changes it brings to media ecosystems.",
          tags: ["Algorithmic ethics", "Deepfakes", "Digital governance", "Automation", "Cultural creation"],
        },
        {
          eje: "Democracy",
          title: "Disinformation, democracy and the quality of public debate",
          desc: "The dynamics of disinformation, post-truth and political polarisation: narrative and emotional manipulation, the role of platforms and fact-checking tools.",
          tags: ["Post-truth", "Fact-checking", "Polarisation", "Platforms"],
        },
        {
          eje: "Rights",
          title: "Digital rights, regulation and networked citizenship",
          desc: "Legal, political and social challenges of digital transformation: regulation of platforms and artificial intelligence, privacy, intellectual property and the liability of digital actors.",
          tags: ["Privacy", "Data protection", "Intellectual property", "Regulation"],
        },
        {
          eje: "Diversity",
          title: "Diversity, inclusive communication and digital cultures",
          desc: "Communication, cultural identities and social change on networks and platforms: hate speech, discrimination and symbolic violence, alongside inclusive communication strategies.",
          tags: ["Hate speech", "Inclusion", "Representation", "Communities", "Digital cultures"],
        },
        {
          eje: "Learning",
          title: "Media education, digital literacy and knowledge transfer",
          desc: "Critical training for technological challenges: media and algorithmic literacy, teaching innovation, digital citizenship and science communication.",
          tags: ["Media literacy", "Teaching innovation", "Science communication", "Digital citizenship"],
        },
        {
          eje: "Future",
          title: "Ethics, sustainability and the future of communication",
          desc: "Ethical, democratic and humanistic challenges of hyperconnectivity: digital sustainability, social responsibility and fundamental rights in automated environments.",
          tags: ["Digital sustainability", "Social responsibility", "Foresight", "Fundamental rights"],
        },
      ],
    },
    aneca: {
      label: "New · 6th edition",
      title: "Workshop on preparing ANECA accreditation",
      lead: "This year, at no extra cost, you can attend a two-hour practical workshop on preparing your accreditation before ANECA's Social Sciences II Committee.",
      talleres: [
        { dia: "3 December", title: "Tenured University Lecturer", desc: "A two-hour practical workshop on preparing the application for tenure." },
        { dia: "4 December", title: "Full Professor", desc: "A two-hour practical workshop on preparing the application for a full professorship." },
      ],
      puntos: [
        { n: "i", t: "Assessment criteria", d: "Particular attention to the criteria of the Social Sciences II Committee." },
        { n: "ii", t: "Preparing the application", d: "How to approach the accreditation file." },
        { n: "iii", t: "Questions", d: "Open time for participants' questions." },
      ],
      nota: "Included in the cost of taking part in Intracom 2026.",
    },
    participacion: {
      label: "03 · Participation",
      title: "Three ways to take part",
      lead: "Submit your proposal in Spanish, English or Portuguese.",
      items: [
        { tag: "On site", title: "On-site participant", desc: "Share your research at the conference venue, with a paper or a poster, and join the sessions." },
        { tag: "Online, live", title: "Online participant", desc: "Take part from anywhere in the world in the online day on 2 December, without travelling." },
        { tag: "Online, recorded", title: "Recorded paper", desc: "Send the video of your paper: it is presented during the conference and you receive the materials and comments afterwards." },
      ],
      requisitos: {
        title: "What your proposal must include",
        items: [
          { t: "Title", d: "Clear, and not in block capitals." },
          { t: "Abstract as PDF", d: "300–500 words: objectives, method, results and conclusions." },
          { t: "Keywords", d: "Four to six terms." },
          { t: "Thematic panel", d: "The main one; if it crosses several, say so." },
          { t: "Authorship", d: "Name, affiliation, country and email of every author." },
        ],
      },
    },
    tarifas: {
      label: "04 · Fees",
      title: "Choose your registration",
      lead: "Every author registers under the fee that applies to them. Prices include taxes.",
      presencial: "On site",
      online: "Online",
      items: [
        { grupo: "presencial", precio: "€160", title: "On-site participant", desc: "First author and additional authors who attend. Includes the ANECA workshops.", destacada: true },
        { grupo: "presencial", precio: "€210", title: "With networking activity", desc: "All the rights of the standard registration plus a working dinner with other participants." },
        { grupo: "presencial", precio: "€260", title: "With scientific publication", desc: "Includes the right to take part in blind peer review. Payment does not guarantee publication." },
        { grupo: "presencial", precio: "€310", title: "Full registration", desc: "For first authors attending on site: networking and publication with an SPI-ranked publisher." },
        { grupo: "presencial", precio: "€120", title: "Additional author, not attending", desc: "For authors of an on-site paper who do not attend the conference." },
        { grupo: "online", precio: "€100", title: "Standard online registration", desc: "Participation in the online day on 2 December, live or pre-recorded." },
        { grupo: "online", precio: "€80", title: "Additional author, online", desc: "For authors of a paper presented online." },
        { grupo: "online", precio: "€200", title: "Online with publication", desc: "Online participation with the right to take part in peer review for publication." },
      ],
      cta: "Register",
      nota: "Registration opens once the committee accepts your proposal. The invoice can be downloaded from your private area as soon as payment is confirmed.",
    },
    fechas: {
      label: "05 · Calendar",
      title: "Key dates",
      items: [
        { fecha: "25 October 2026", t: "Deadline for proposals", d: "Papers, posters and book presentations." },
        { fecha: "28 October 2026", t: "Notification of the decision", d: "The scientific committee communicates its decision." },
        { fecha: "31 October 2026", t: "Registration closes", d: "Last day to complete payment." },
        { fecha: "10 November 2026", t: "Final programme", d: "Publication of the conference programme." },
        { fecha: "2–4 December 2026", t: "The conference", d: "Online day on the 2nd; on site on the 3rd and 4th." },
      ],
    },
    publicaciones: {
      label: "06 · Publications",
      title: "From the paper to scientific publication",
      paragraphs: [
        "Taking part in the conference and publishing are two separate processes: presenting a paper does not oblige you to send the full text afterwards.",
        "Those who wish to be considered for publication submit the full text within the deadline, following the editorial guidelines, for blind peer review. Editorial management costs an additional €100 per paper, not per author, and may be paid by any of the authors.",
        "Papers that pass review are published by partner academic publishers. If a proposal is not accepted, it may be included, subject to scientific assessment, in Intracom's collective volumes or in the journals linked to the portal.",
      ],
      editoriales: { title: "Partner publishers", items: ["Tirant lo Blanch", "Dykinson", "Fragua", "Tecnos"] },
      revistas: { title: "Journals in this edition", items: ["Dígitos", "Perspectivas de la Comunicación", "Intracom Journal"] },
    },
    organizacion: {
      label: "07 · Organisation",
      title: "Who is behind it",
      grupos: null,
    },
    sede: {
      label: "08 · Venue",
      title: "University of La Laguna, Tenerife",
      paragraphs: [
        "The conference takes place at the Faculty of Social Sciences and Communication, on the Guajara Campus, with the collaboration of the IACTEC facilities of the Instituto de Astrofísica de Canarias.",
        "Tenerife was chosen for its position between three continents, a mirror of the Ibero-American character of the conference, and for its closeness and sensitivity to the problems of the global south. The open, multicultural character of the Canary Islands makes for a welcoming setting.",
      ],
      direccion: "Guajara Campus · University of La Laguna · Santa Cruz de Tenerife, Canary Islands",
      mapa: "See the location on the map →",
    },
    footer: {
      desc: "6th International Conference on Research and Knowledge Transfer in Communication and Science Communication.",
      menu: "Sections",
      contacto: "Contact",
      red: "Network conferences",
      legal: "Legal notice",
      privacidad: "Privacy",
      cookies: "Cookies",
      condiciones: "Registration terms",
      copy: "Intracom Conference · Ibero-American Portal for Knowledge Transfer",
      portal: "Portal Intracom ↗",
    },
  },

  pt: {
    lang: "pt",
    meta: {
      title: "VI Congresso Internacional Intracom · Tenerife 2026",
      description:
        "VI Congresso Internacional de Investigação e Transferência em Comunicação e Divulgação das Ciências. Universidade de La Laguna, 2 a 4 de dezembro de 2026. Propostas até 25 de outubro.",
    },
    nav: {
      congreso: "O congresso",
      mesas: "Mesas temáticas",
      participacion: "Participação",
      tarifas: "Tarifas",
      publicaciones: "Publicações",
      organizacion: "Organização",
      sede: "Local",
      cta: "Inscreva-se",
    },
    hero: {
      eyebrow: "VI Congresso Internacional · Tenerife 2026",
      title: "Direito e comunicação crítica",
      titleAccent: "perante o algoritmo",
      lead: "Congresso Internacional de Investigação e Transferência em Comunicação e Divulgação das Ciências.",
      chips: [
        { label: "Presencial", value: "3 e 4 de dezembro de 2026" },
        { label: "Online", value: "2 de dezembro de 2026" },
        { label: "Local", value: "Universidade de La Laguna · Tenerife" },
      ],
      cta1: "Apresente a sua proposta",
      cta2: "Ver as mesas temáticas",
      bar: "Envio de comunicações aberto até 25 de outubro de 2026",
      barCta: "Como participar →",
    },
    stats: [
      { n: "VI", l: "edição do congresso" },
      { n: "6", l: "mesas temáticas" },
      { n: "2", l: "workshops ANECA incluídos" },
      { n: "3", l: "idiomas de participação" },
    ],
    about: {
      label: "01 · Apresentação",
      title: "Repensar a comunicação quando o algoritmo decide",
      paragraphs: [
        "Vivemos um momento marcado por transformações tecnológicas, culturais e políticas que alteram as formas de produzir, distribuir e legitimar a informação. A inteligência artificial generativa, o poder das plataformas e a automatização algorítmica configuraram um ecossistema mediático de hiperconectividade, excesso de informação e aceleração da opinião pública.",
        "Nesse contexto, a desinformação, os discursos de ódio, a polarização e a manipulação emocional das audiências são alguns dos principais desafios para as democracias. A crise de confiança nas instituições e a expansão de narrativas extremistas obrigam a repensar as relações entre comunicação, direitos fundamentais e cidadania digital.",
        "A inteligência artificial intensifica estas tensões: ferramentas capazes de gerar textos, imagens, vídeos ou vozes sintéticas levantam questões sobre a veracidade dos conteúdos, a autoria, a responsabilidade jurídica e os limites éticos da automatização comunicativa.",
        "Por isso propomos um espaço de reflexão interdisciplinar que analise criticamente estas transformações a partir de perspetivas jurídicas, educativas, éticas e sociais, tendo como eixo a defesa dos direitos humanos e de uma comunicação democrática.",
      ],
    },
    mesas: {
      label: "02 · Mesas temáticas",
      title: "Seis linhas para repensar a comunicação digital",
      lead: "As mesas são permeáveis: uma proposta pode cruzar dois ou mais eixos. Indique-o ao enviá-la.",
      items: [
        {
          eje: "Inteligência artificial",
          title: "Inteligência artificial, ecossistemas mediáticos e governação digital",
          desc: "O impacto da inteligência artificial nos processos de comunicação, informação e produção cultural, e as transformações que introduz nos ecossistemas mediáticos.",
          tags: ["Ética algorítmica", "Deepfakes", "Governação digital", "Automatização", "Criação cultural"],
        },
        {
          eje: "Democracia",
          title: "Desinformação, democracia e qualidade do debate público",
          desc: "Dinâmicas da desinformação, da pós-verdade e da polarização política: manipulação narrativa e emocional, o papel das plataformas e as ferramentas de verificação.",
          tags: ["Pós-verdade", "Fact-checking", "Polarização", "Plataformas"],
        },
        {
          eje: "Direitos",
          title: "Direitos digitais, regulação e cidadania em rede",
          desc: "Desafios jurídicos, políticos e sociais da transformação digital: regulação de plataformas e inteligência artificial, privacidade, propriedade intelectual e responsabilidade dos atores digitais.",
          tags: ["Privacidade", "Proteção de dados", "Propriedade intelectual", "Regulação"],
        },
        {
          eje: "Diversidade",
          title: "Diversidade, comunicação inclusiva e culturas digitais",
          desc: "Comunicação, identidades culturais e transformação social em redes e plataformas: discursos de ódio, discriminação e violência simbólica, a par de estratégias de comunicação inclusiva.",
          tags: ["Discursos de ódio", "Inclusão", "Representação", "Comunidades", "Culturas digitais"],
        },
        {
          eje: "Aprendizagem",
          title: "Educação mediática, literacia digital e transferência do conhecimento",
          desc: "Formação crítica perante os desafios tecnológicos: literacia mediática e algorítmica, inovação docente, cidadania digital e divulgação científica.",
          tags: ["Literacia mediática", "Inovação docente", "Divulgação científica", "Cidadania digital"],
        },
        {
          eje: "Futuro",
          title: "Ética, sustentabilidade e futuro da comunicação",
          desc: "Desafios éticos, democráticos e humanísticos da hiperconectividade: sustentabilidade digital, responsabilidade social e direitos fundamentais em ambientes automatizados.",
          tags: ["Sustentabilidade digital", "Responsabilidade social", "Prospetiva", "Direitos fundamentais"],
        },
      ],
    },
    aneca: {
      label: "Novidade · VI edição",
      title: "Seminário de preparação de acreditações ANECA",
      lead: "Este ano, pelo mesmo custo de participação, pode assistir a um workshop prático de duas horas orientado para a preparação da sua acreditação perante a Comissão de Ciências Sociais II da ANECA.",
      talleres: [
        { dia: "3 de dezembro", title: "Professor/a Titular de Universidade", desc: "Workshop prático de duas horas dirigido à preparação da acreditação a Professor/a Titular." },
        { dia: "4 de dezembro", title: "Catedrático/a de Universidade", desc: "Workshop prático de duas horas dirigido à preparação da acreditação a Catedrático/a." },
      ],
      puntos: [
        { n: "i", t: "Critérios de avaliação", d: "Atenção especial aos critérios da Comissão de Ciências Sociais II." },
        { n: "ii", t: "Preparação da candidatura", d: "Como abordar a preparação do processo de acreditação." },
        { n: "iii", t: "Esclarecimento de dúvidas", d: "Espaço aberto às perguntas de quem participa." },
      ],
      nota: "Incluído no custo de participação no Intracom 2026.",
    },
    participacion: {
      label: "03 · Participação",
      title: "Três formas de participar",
      lead: "Apresente a sua proposta em espanhol, inglês ou português.",
      items: [
        { tag: "Presencial", title: "Congressista presencial", desc: "Partilhe a sua investigação no local do congresso, com uma comunicação científica ou um póster, e participe nas sessões." },
        { tag: "Online em direto", title: "Congressista online", desc: "Participe de qualquer parte do mundo na jornada virtual de 2 de dezembro, sem se deslocar." },
        { tag: "Online em diferido", title: "Comunicação gravada", desc: "Envie o vídeo da sua comunicação: é apresentada durante o congresso e recebe depois os materiais e os comentários." },
      ],
      requisitos: {
        title: "O que deve incluir a sua proposta",
        items: [
          { t: "Título", d: "Claro e sem maiúsculas em todo o texto." },
          { t: "Resumo em PDF", d: "Entre 300 e 500 palavras: objetivos, método, resultados e conclusões." },
          { t: "Palavras-chave", d: "De quatro a seis termos." },
          { t: "Mesa temática", d: "A principal; se cruzar várias, indique-o." },
          { t: "Autoria", d: "Nome, filiação, país e correio de cada subscritor." },
        ],
      },
    },
    tarifas: {
      label: "04 · Tarifas",
      title: "Escolha a sua inscrição",
      lead: "Cada pessoa subscritora inscreve-se com a tarifa que lhe corresponde. Preços com impostos incluídos.",
      presencial: "Modalidade presencial",
      online: "Modalidade online",
      items: [
        { grupo: "presencial", precio: "160 €", title: "Congressista presencial", desc: "Primeiro subscritor e subscritores adicionais que assistem. Inclui os workshops ANECA.", destacada: true },
        { grupo: "presencial", precio: "210 €", title: "Com atividade de networking", desc: "Todos os direitos da inscrição básica mais um jantar de trabalho com outras pessoas participantes." },
        { grupo: "presencial", precio: "260 €", title: "Com publicação científica", desc: "Inclui o direito a participar na avaliação por pares cega. O pagamento não garante a publicação." },
        { grupo: "presencial", precio: "310 €", title: "Inscrição completa", desc: "Para primeiros subscritores presenciais: networking e publicação em editora do ranking SPI." },
        { grupo: "presencial", precio: "120 €", title: "Subscritor adicional sem presença", desc: "Para subscritores de uma comunicação presencial que não assistem ao congresso." },
        { grupo: "online", precio: "100 €", title: "Inscrição básica online", desc: "Participação na jornada online de 2 de dezembro, em direto ou em diferido." },
        { grupo: "online", precio: "80 €", title: "Subscritor adicional online", desc: "Para subscritores de uma comunicação apresentada na modalidade online." },
        { grupo: "online", precio: "200 €", title: "Online com publicação", desc: "Modalidade online com direito a participar na avaliação por pares para publicação." },
      ],
      cta: "Inscrever-me",
      nota: "A inscrição abre quando a comissão aceita a sua proposta. A fatura descarrega-se na sua área privada assim que o pagamento é confirmado.",
    },
    fechas: {
      label: "05 · Calendário",
      title: "Datas importantes",
      items: [
        { fecha: "25 de outubro de 2026", t: "Fim do envio de propostas", d: "Comunicações, pósteres e apresentações de livro." },
        { fecha: "28 de outubro de 2026", t: "Notificação do resultado", d: "A comissão científica comunica a sua decisão." },
        { fecha: "31 de outubro de 2026", t: "Fim das inscrições", d: "Último dia para formalizar o pagamento." },
        { fecha: "10 de novembro de 2026", t: "Programa definitivo", d: "Publicação do programa do congresso." },
        { fecha: "2 a 4 de dezembro de 2026", t: "Realização do congresso", d: "Jornada online a 2; presencial a 3 e 4." },
      ],
    },
    publicaciones: {
      label: "06 · Publicações",
      title: "Da comunicação à publicação científica",
      paragraphs: [
        "Participar no congresso e publicar são dois processos independentes: apresentar uma comunicação não obriga a enviar depois o texto completo.",
        "Quem quiser candidatar-se à publicação envia o texto completo no prazo previsto, seguindo as normas editoriais, para avaliação por pares cega. A gestão editorial tem um custo adicional de 100 € por comunicação, não por subscritor, que pode ser assumido por qualquer um dos autores.",
        "Os trabalhos que superam a avaliação são publicados por editoras académicas parceiras. Se uma proposta não for aceite, pode ser incorporada, após valoração científica, em volumes coletivos do Intracom ou nas revistas ligadas ao portal.",
      ],
      editoriales: { title: "Editoras parceiras", items: ["Tirant lo Blanch", "Dykinson", "Fragua", "Tecnos"] },
      revistas: { title: "Revistas desta edição", items: ["Dígitos", "Perspectivas de la Comunicación", "Intracom Journal"] },
    },
    organizacion: {
      label: "07 · Organização",
      title: "Quem está por trás",
      grupos: null,
    },
    sede: {
      label: "08 · Local",
      title: "Universidade de La Laguna, Tenerife",
      paragraphs: [
        "O congresso realiza-se na Faculdade de Ciências Sociais e da Comunicação, no Campus de Guajara, com a colaboração das instalações do IACTEC do Instituto de Astrofísica de Canarias.",
        "Tenerife foi escolhida pela sua posição entre três continentes, espelho do carácter ibero-americano do congresso, e pela proximidade e sensibilidade aos problemas do sul global. O carácter aberto e multicultural das Canárias cria um ambiente propício ao encontro entre colegas.",
      ],
      direccion: "Campus de Guajara · Universidade de La Laguna · Santa Cruz de Tenerife, Ilhas Canárias",
      mapa: "Ver localização no mapa →",
    },
    footer: {
      desc: "VI Congresso Internacional de Investigação e Transferência em Comunicação e Divulgação das Ciências.",
      menu: "Secções",
      contacto: "Contacto",
      red: "Congressos da rede",
      legal: "Aviso legal",
      privacidad: "Privacidade",
      cookies: "Cookies",
      condiciones: "Condições de inscrição",
      copy: "Congresso Intracom · Portal Ibero-Americano da Transferência do Conhecimento",
      portal: "Portal Intracom ↗",
    },
  },
};

// El comité es el mismo en los tres idiomas: nombres propios y universidades no se traducen
window.INTRACOM_CONTENT.en.organizacion.grupos = [
  { title: "Steering team", personas: window.INTRACOM_CONTENT.es.organizacion.grupos[0].personas },
  { title: "Scientific committee", personas: window.INTRACOM_CONTENT.es.organizacion.grupos[1].personas },
  { title: "Secretariat and organisation", personas: window.INTRACOM_CONTENT.es.organizacion.grupos[2].personas },
];
window.INTRACOM_CONTENT.pt.organizacion.grupos = [
  { title: "Equipa de direção", personas: window.INTRACOM_CONTENT.es.organizacion.grupos[0].personas },
  { title: "Comissão científica", personas: window.INTRACOM_CONTENT.es.organizacion.grupos[1].personas },
  { title: "Secretariado e organização", personas: window.INTRACOM_CONTENT.es.organizacion.grupos[2].personas },
];
